// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qdyfzevhmphbndwlbkwt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFkeWZ6ZXZobXBoYm5kd2xia3d0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA1MjIwNDAsImV4cCI6MjA2NjA5ODA0MH0.-iltBCxPwE6Zoa_FJmIns5mWqwMQdRxflsHXcKvHgyo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);